### ISSUE TITLE
No Filter Folders for J+Ch4-1.2

### ISSUE THREAD

**Issue by cdressing** [arjunsavel/SImMER#134]
**Describe the bug**

When making folders based on filters, SImMER groups J+Ch4-1.2 observations together with J band observations. 

**To Reproduce**

**Expected behavior**

Both filters should be considered when setting the filter-based filenames. Observations taken in J+Ch4-1.2 should be stored separately from those taken in J.

**Screenshots**

**Additional context**

**Comment by arjunsavel** [comment]
Addressed in #130 !
