### ISSUE TITLE
Skies-Labelled Stars

### ISSUE THREAD

**Issue by holdengill** [arjunsavel/SImMER#75]
When a star has an additional label 'skies' after the ID number, it screws up the final output image/registration. The 'skies' term must be removed from the 'object' column, and a new column labelled 'comments' must be added, where you put 'sky' for the previously labeled 'skies' objects. 

Then when instantiating, need to use 'take_skies=True'. This currently results in the registration not identifying any objects, and the all_driver code stops once it reaches the skies portion.

**Comment by arjunsavel** [comment]
I think this has been resolved in #78. Thanks for reporting this!
