### ISSUE TITLE
Modules not accepting .xlsx files for log sheets

### ISSUE THREAD

**Issue by holdengill** [arjunsavel/SImMER#89]
check_logsheet, create_config, add_darks, etc. not accepting .xlsx files for the log sheets. Must convert to .csv. See photos below for error (this one is create_config).

![image](https://user-images.githubusercontent.com/62360469/112537779-5101f800-8d6c-11eb-9f6e-e971902adda7.png)
![image](https://user-images.githubusercontent.com/62360469/112537805-595a3300-8d6c-11eb-964e-63bf7d2d6219.png)

**Comment by arjunsavel** [comment]
Great catch! Will likely look into something like openpyxl...I'll also need to make sure tests are run on my end more frequently!

**Comment by arjunsavel** [comment]
Addressed in #91.
