### ISSUE TITLE
Config File method column syntax

### ISSUE THREAD

**Issue by holdengill** [arjunsavel/SImMER#90]
The config files require each target have 'saturated' in the 'Method' column. Cannot be capitalized (i.e. 'Saturated' does not work). The error received if you put a capitalized 'S' is screenshotted below, and it happens during registration:

![image](https://user-images.githubusercontent.com/62360469/112557183-1a86a600-8d89-11eb-93f2-7f36f6cd2c0d.png)

**Comment by arjunsavel** [comment]
Addressed in 4e1abda20b94124a1f679f48cb227803d2cdd543.
